tasks:
    - init: pip3 install -r requirements.txt
      command: python3 main.py
vscode:
    extensions:
        - almenon.arepl
        - littlefoxteam.vscode-python-test-adapter@0.3.16:tZ/6xOSSdKUaq6JCUVkD+A==